#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.7
# apt-get -y update
# apt-get install -y haproxy=2.7.\*

sudo apt-get install haproxy=2.7.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobi
   option httpclose
   option forwardfor
   server 57528-web-01  18.235.255.74:80 check
   server 57528-web-02 54.90.12.111:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
